trigger:
  branches:
    include:
    - main
    exclude:
      - README.md
  
stages:
  - stage: Test
    displayName: Test
    jobs:
    - job: init
      displayName: Terraform testing
      pool:
        vmImage: ubuntu-latest
      steps:

      
      - task: AzurePowerShell@5
        inputs:
#          azureSubscription: 'Azure subscription 1(3af17bf0-3584-4f14-8c52-8d07a62a7737)'
          azureSubscription: 'pipeline-connection'
          ScriptType: 'InlineScript'
          Inline: |
            terraform init
            terraform plan --out tfplan.binary
            terraform show -json tfplan.binary | jq > tfplan.json
          azurePowerShellVersion: 'LatestVersion'
          workingDirectory: '$(build.sourcesdirectory)'
        displayName: Terraform init
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            pip install checkov
            checkov -f tfplan.json > scan-results.xml
        displayName: Checkov
        continueOnError: true
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          testResultsFiles: '**/*scan-result.xml'
          mergeTestResults: false
          testRunTitle: Terraform source code scan
          failTaskOnFailedTests: false
          publishRunAttachments: true
        displayName: Publish Test Result