trigger:
  branches:
    include:
    - main
    exclude:
      - README.md
  
stages:
  - stage: Test
    displayName: Test
    jobs:
    - job: init
      displayName: Terraform testing
      pool:
        vmImage: ubuntu-latest
      steps:
      - task: AzureCLI@2
        inputs:
          azureSubscription: 'pipeline-connection'
          scriptType: 'batch'
          scriptLocation: 'inlineScript'
          inlineScript: |
            terraform init
            terraform plan --out tfplan.binary
            terraform show -json tfplan.binary | jq > tfplan.json
#      - task: PowerShell@2
#        inputs:
#          targetType: 'inline'
#          script: |
#             terraform init
#            terraform plan --out tfplan.binary
#            terraform show -json tfplan.binary | jq > tfplan.json
#          workingDirectory: '$(build.sourcesdirectory)'
#        displayName: Terraform init
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            pip install checkov
            checkov -f tfplan.json > scan-results.xml
        displayName: Checkov
        continueOnError: true
      - task: PublishTestResults@2
        inputs:
          testResultsFormat: 'JUnit'
          searchFolder: '$(System.DefaultWorkingDirectory)'
          testResultsFiles: '**/*scan-result.xml'
          mergeTestResults: false
          testRunTitle: Terraform source code scan
          failTaskOnFailedTests: false
          publishRunAttachments: true
        displayName: Publish Test Result